### ISSUE TITLE
archive project on windows

### ISSUE THREAD

**Issue by x0rld** [Wmanage/wng#12]
on windows no one has tar installed, you should use the [win api](https://docs.microsoft.com/en-us/windows/win32/api/compressapi/) if you can, it can compress to all theses formats.
![image](https://user-images.githubusercontent.com/45242856/97793543-aab32b80-1bed-11eb-8b21-9da7e5648827.png)

**Comment by Wafelack** [comment]
It won't be cross platform is i use the winapi. There is a link to download tar on windows in the README.


Rejected

**Comment by AntoineJT** [comment]
You can detect platform at compile-time like in C or C++ with macros.
I do this [in this function](https://github.com/AntoineJT/shell-compiler/blob/master/src/main.rs#L90) for example.
It will be worth to take a look at [this](https://doc.rust-lang.org/rust-by-example/attribute/cfg.html) (Rust by example cfg macro page).

**Comment by glcraft** [comment]
> It won't be cross platform is i use the winapi. There is a link to download tar on windows in the README.
> 
> Rejected

A cross platform program doesn't mean you don't have to use OS specific code. 
It means that you have to be compatible between systems by making equivalent code for each system if needed.

You could also use a cross platform dependency which can read tarball.

**Comment by Wafelack** [comment]
Done in #19
