### ISSUE TITLE
Publishing/installing lib

### ISSUE THREAD

**Issue by SuperFola** [Wmanage/wng#4]
This is related to https://github.com/Wmanage/wng#publish-your-library and https://github.com/Wmanage/wng#to-install-a-library

I suggest using github as the host for the libraries, instead of sending them to you for them to be hosted on a website (because in that case we would need to send you every version and that's quite annoying).
The idea would be to have a wng.json in each repository for example, with informations about the module, thus allowing the command `wng query <module>` to check if it's a wng module or not, and if it exists or not.
Then since the modules will be hosted on github, maybe something like `wng install github.com:username/repository` would be better than just `wng install repository` (`github.com:` as a prefix in case you want to handle gitlab, bitbucket and more).

This way, no need to buy a server where the user will have to push their code as well as on their github repo, and it's easier to maintain for everyone.

**Comment by Wafelack** [comment]
Ok let's try that. Found [that](https://gist.github.com/KazeroG/ed8c88928e5a7a3383f606546a9fa3f4) on the internet.

**Comment by Wafelack** [comment]
@SuperFola Ok It is pretty finished, it works but i have a little problem with folder deletion, but it is correct.

I also modified README => [here](https://github.com/Wmanage/wng#to-install-a-library) and [here](https://github.com/Wmanage/wng#publish-your-library)
