### ISSUE TITLE
Use a programming language for build scripts

### ISSUE THREAD

**Issue by Iltotore** [Wmanage/wng#8]
Hello,
WNG should use a programming language like Rust instead of JSON to allow more customisable builds and enhance flexibility. 

For example Gradle uses Groovy/KotlinScript and Mill uses Scala.

I will provide further informations once I finish school.

**Comment by Wafelack** [comment]
See [6bbd734](https://github.com/Wmanage/wng/commit/6bbd73466b9ea9bae58a616a0296b3afc763b1c0). Is it good ?

**Comment by SuperFola** [comment]
You are spawning a process using the command python but you should check if it's a 2.x version or a 3.x and set a minimum version required as well

**Comment by Wafelack** [comment]
hmmm in fact i can just run with the command `python3` but i'm not sure it works for windows ...

**Comment by Wafelack** [comment]
@SuperFola Is that correct for you ? [749b89e](https://github.com/Wmanage/wng/commit/749b89e454edb651a08428ab1a7f6f6c2afe0d30)

**Comment by SuperFola** [comment]
Yep that's much better!

**Comment by Iltotore** [comment]
> @SuperFola Is that correct to you ? [749b89e](https://github.com/Wmanage/wng/commit/749b89e454edb651a08428ab1a7f6f6c2afe0d30)

You should allow python executable path specification and pick from an env variable by default.
